# Generated by Django 5.0.3 on 2024-03-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUFC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lutadormodel',
            name='ultimaLuta',
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='evento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='lutador1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do lutador'),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='lutador2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do lutador'),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='metodo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Método de vitória'),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='rounds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='lutadormodel',
            name='vencedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vencedor'),
        ),
        migrations.DeleteModel(
            name='UltimaLutaModel',
        ),
    ]
