# Generated by Django 5.0.3 on 2024-03-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUFC', '0004_alter_lutadormodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutadormodel',
            name='totalDeLutas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lutadormodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
