# Generated by Django 5.0.3 on 2024-03-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUFC', '0003_remove_lutadormodel_data_remove_lutadormodel_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutadormodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
