# Generated by Django 5.0.3 on 2024-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUFC', '0005_lutadormodel_totaldelutas_alter_lutadormodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutadormodel',
            name='cartel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cartel do lutador v-d-nc'),
        ),
        migrations.AlterField(
            model_name='lutadormodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
